// Generated by React Router

import "react-router";

declare module "react-router" {
  interface Register {
    pages: Pages;
    routeFiles: RouteFiles;
    routeModules: RouteModules;
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/monster": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/monster";
  };
  "./components/handbook/Monster.tsx": {
    id: "components/handbook/Monster";
    page: "/monster";
  };
};

type RouteModules = {
  root: typeof import("./app/root.tsx");
  "components/handbook/Monster": typeof import("./app/./components/handbook/Monster.tsx");
};
